# Generated by Django 4.1.1 on 2022-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_book_author_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
