# Generated by Django 4.1.1 on 2022-09-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='AuthorImageUrl',
            new_name='authorImageUrl',
        ),
    ]
