# Generated by Django 4.1.1 on 2022-09-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_authorimageurl_author_authorimageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='GenreImageUrl',
            new_name='genresImageUrl',
        ),
    ]
