# Generated by Django 4.1.1 on 2022-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
