# Generated by Django 4.1.1 on 2022-09-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='book_image',
        ),
    ]
