# Generated by Django 4.1.1 on 2022-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=2, verbose_name='pages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='qty'),
        ),
    ]
