# Generated by Django 4.1.1 on 2022-09-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_book_pages_book_rate_alter_order_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='book',
            name='saved',
            field=models.BooleanField(default=True, verbose_name='is saved'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='totalPrice'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='rate'),
        ),
    ]
