# Generated by Django 4.1.1 on 2022-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_book_top_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='saved',
            field=models.BooleanField(verbose_name='is_saved'),
        ),
        migrations.AlterField(
            model_name='book',
            name='top_rated',
            field=models.BooleanField(verbose_name='top_rated'),
        ),
    ]
