# Generated by Django 4.1.1 on 2022-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_book_saved_alter_book_top_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='rate'),
        ),
    ]
