# Generated by Django 4.1.1 on 2022-09-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_items_saved_books_remove_order_desiredbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='savedBooks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='backend.saved_books', verbose_name='savedbook'),
        ),
    ]
