# Generated by Django 4.1.1 on 2022-09-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_book_savedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_books',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.book', verbose_name='saved_Books'),
        ),
    ]
