# Generated by Django 4.1.1 on 2022-09-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_items_remove_order_desiredbook_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='inCart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='isBought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
