# Generated by Django 4.1.1 on 2022-09-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_saved_books_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='savedBooks',
        ),
        migrations.AlterField(
            model_name='saved_books',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='here', to='backend.book', verbose_name='saved_Books'),
        ),
        migrations.AddField(
            model_name='book',
            name='savedBooks',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='backend.saved_books', verbose_name='savedbook'),
        ),
    ]
