# Generated by Django 4.1.1 on 2022-09-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_items_incart_alter_items_isbought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_sales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
