# Generated by Django 4.1.1 on 2022-09-09 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0017_book_total_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('saved', models.BooleanField(verbose_name='is_saved')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='backend.book', verbose_name='saved_Books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_saved_Books')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
