# Generated by Django 4.1.1 on 2022-09-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_book_savedbooks_alter_saved_books_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('ARABIC', 'ARABIC'), ('ENGLISH', 'ENglish')], default=1, max_length=10, verbose_name='Language'),
            preserve_default=False,
        ),
    ]
