# Generated by Django 4.1.1 on 2022-09-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English')], max_length=10, verbose_name='Language'),
        ),
    ]
