# Generated by Django 4.1.1 on 2022-09-09 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_savedbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedbooks',
            name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='saved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='backend.savedbooks', verbose_name=''),
        ),
    ]
