# Generated by Django 4.1.1 on 2022-09-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_savedbooks_book_alter_book_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='saved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='backend.savedbooks', verbose_name='saved'),
        ),
    ]
