# Generated by Django 4.1.1 on 2022-09-09 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0020_author_image_author_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created',
        ),
        migrations.RemoveField(
            model_name='author',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='created',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='items',
            name='created',
        ),
        migrations.RemoveField(
            model_name='items',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='saved_books',
            name='created',
        ),
        migrations.RemoveField(
            model_name='saved_books',
            name='updated',
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateField(auto_now_add=True, default="1999-6-23"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saved_books',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='here', to='backend.book', verbose_name='saved_Books'),
        ),
        migrations.AlterField(
            model_name='saved_books',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_saved_Books'),
        ),
    ]
