# Generated by Django 4.1.1 on 2022-09-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_book_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='saved',
        ),
    ]
