# Generated by Django 4.1.1 on 2022-09-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_book_saved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedBooks',
        ),
    ]
