# Generated by Django 4.1.1 on 2022-09-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_book_bookimageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='savedBooks',
        ),
    ]
