# Generated by Django 4.1.1 on 2022-09-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_book_bookimageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_image',
        ),
    ]
