# Generated by Django 4.1.1 on 2022-09-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_remove_book_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='image',
        ),
        migrations.AddField(
            model_name='author',
            name='bookImageUrl',
            field=models.URLField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Blank_button.svg/1200px-Blank_button.svg.png', null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='bookImageUrl',
            field=models.URLField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Blank_button.svg/1200px-Blank_button.svg.png', null=True),
        ),
    ]
