# Generated by Django 4.1.1 on 2022-09-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_remove_author_image_remove_genre_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bookImageUrl',
            new_name='AuthorImageUrl',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='bookImageUrl',
            new_name='GenreImageUrl',
        ),
    ]
