# Generated by Django 4.1.1 on 2022-09-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_rename_bookimageurl_author_authorimageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated',
        ),
    ]
